//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultantTopics
    {
        public int ID { get; set; }
        public int ConsultantID { get; set; }
        public int TopicID { get; set; }
    
        public virtual Consultants Consultants { get; set; }
        public virtual Topics Topics { get; set; }
    }
}
