//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultants()
        {
            this.ConsultantTopics = new HashSet<ConsultantTopics>();
            this.ConsultationRequests = new HashSet<ConsultationRequests>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public int Experience { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultantTopics> ConsultantTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationRequests> ConsultationRequests { get; set; }
    }
}
