//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultPlanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultPlannerEntities : DbContext
    {
        public ConsultPlannerEntities()
            : base("name=ConsultPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultants> Consultants { get; set; }
        public virtual DbSet<ConsultantTopics> ConsultantTopics { get; set; }
        public virtual DbSet<ConsultationRequests> ConsultationRequests { get; set; }
        public virtual DbSet<Feedbacks> Feedbacks { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SessionMessages> SessionMessages { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<SessionTopics> SessionTopics { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Topics> Topics { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
